var1=input("introduce la primera palabra:")
var2=input("introduce la segunda palabra:")
var3=input("introduce la tercera palabra:")
var4=input("introduce la cuarta palbra:")
var5=input("introduce la quinta palabra:")
print(f"{var5}, {var4}, {var3}, {var2}, {var1}")